Added endpoint for getting user by role
ApCyb-2025-team-3/community-data-control pull request #23
Opened 2023-11-02 20:07 UTC by MaxLost

2023-11-03 19:25 UTC, vadim65060 requested changes

2023-11-03 19:25 UTC, vadim65060 commented on src/main/java/edu/spbu/datacontrol/models/enums/EventType.java
> +    public static EventType fromString(String text) {
используй наследование, enum -> enum с методом поиска -> наши енамы

2023-11-03 19:25 UTC, vadim65060 commented on src/test/java/edu/spbu/datacontrol/controllers/UserControllerTest.java
> +        String[] grades = new String[] {"Junior", "Middle", "Senior", "TeamLead"};
в enum (помни о наследовании) добавить метод для получения этих штук

2023-11-03 19:25 UTC, vadim65060 commented on src/test/java/edu/spbu/datacontrol/controllers/UserControllerTest.java
> +    private boolean userDtoComparator(UserDTO user1, UserDTO user2) {
определить оператор для UserDTO

2023-11-03 19:25 UTC, vadim65060 commented on src/test/java/edu/spbu/datacontrol/controllers/UserControllerTest.java
> +    private UserAdditionDTO generateSimpleUser() {
обнови старый тест, используя эту штуку

2023-11-03 19:31 UTC, MaxLost commented on src/test/java/edu/spbu/datacontrol/controllers/UserControllerTest.java
> +        String[] grades = new String[] {"Junior", "Middle", "Senior", "TeamLead"};
Это не будет использоваться нигде кроме тестов, также нужны именно те значения которые указаны (не специальные)

2023-11-03 19:33 UTC, MaxLost commented on src/test/java/edu/spbu/datacontrol/controllers/UserControllerTest.java
> +    private boolean userDtoComparator(UserDTO user1, UserDTO user2) {
Нигде кроме тестов это нам не будет нужно, не уверен что стоит это переносить в метод equals() и усложнять UserDTO

2023-11-04 11:51 UTC, vadim65060 commented on src/test/java/edu/spbu/datacontrol/controllers/UserControllerTest.java
> +    private boolean userDtoComparator(UserDTO user1, UserDTO user2) {
лишним это не будет, как минимум не придётся писать такие костыли

2023-11-05 19:02 UTC, MaxLost commented on src/test/java/edu/spbu/datacontrol/controllers/UserControllerTest.java
> +    private UserAdditionDTO generateSimpleUser() {
+

2023-11-05 19:04 UTC, MaxLost commented on src/main/java/edu/spbu/datacontrol/models/enums/EventType.java
> +    public static EventType fromString(String text) {
Не наследуются в Java enum'ы

2023-11-05 19:05 UTC, MaxLost commented on src/test/java/edu/spbu/datacontrol/controllers/UserControllerTest.java
> +    private boolean userDtoComparator(UserDTO user1, UserDTO user2) {
Убрал совсем сравнение, при переносе в equals() не смог бы его применить в этом месте

2023-11-05 19:24 UTC, vadim65060 approved these changes

2023-11-05 19:30 UTC, merged