Get by sprvsr&dismiss by
ApCyb-2025-team-3/community-data-control pull request #25
Opened 2023-11-06 19:22 UTC by OkatyLee

Create getUsersBySupervisorId & dismissById

2023-11-06 19:52 UTC, MaxLost requested changes

2023-11-06 19:52 UTC, MaxLost commented on src/main/java/edu/spbu/datacontrol/controllers/UserController.java
> +            return  new ResponseEntity<>(event, HttpStatusCode.valueOf(200));
Event это чисто служебная структура данных, не предусматривается, что её нужно кому-то на фронтенд посылать, лучше просто 200 код с фразой об успешной операции, а при ошибке 404 тоже с соответствующей фразой

2023-11-06 19:52 UTC, MaxLost commented on src/main/java/edu/spbu/datacontrol/controllers/UserController.java
> +            return new ResponseEntity<>(HttpStatusCode.valueOf(404));
Тут не очень подходит 404 код, лучше использовать 409, он указывает на конфликт в запросе, а тут как раз такой случай: запрос был на возврат подчинённых руководителя, а присланный пользователь - не руководитель

2023-11-06 19:52 UTC, MaxLost commented on src/test/java/edu/spbu/datacontrol/controllers/UserControllerTest.java
> +        Assertions.assertEquals(id, event.getUserId());
Опять же, Event не предполагается отправлять пользователям на фронтенд, это чисто для внутреннего использования

2023-11-06 19:52 UTC, MaxLost commented on src/test/java/edu/spbu/datacontrol/controllers/UserControllerTest.java
> +            new TypeReference<>() {}
Точно с таким TypeReference всё будет работать?

TypeReference нужен для того, чтобы явно указывать Jackson'у в какой тип данных преобразовывать JSON, а тут его нет.

2023-11-06 19:52 UTC, MaxLost commented on src/test/java/edu/spbu/datacontrol/controllers/UserControllerTest.java
> +        UserAdditionDTO supervisor = new UserAdditionDTO(
Лучше использовать генерацию случайных пользователей, а потом модифицировать их. База данных не чистится между тестами, так что могут быть наложения. 

При генерации пользователя имя <=> id, так как оно генерируется с помощью UUID

2023-11-06 19:52 UTC, MaxLost commented on src/main/java/edu/spbu/datacontrol/repositories/UserRepository.java
> +    List<User> getUsersBySupervisor(User supervisor);
Нет тестов для метода, надо написать в файле UserRepositoryTest.java

2023-11-06 23:20 UTC, OkatyLee commented on src/test/java/edu/spbu/datacontrol/controllers/UserControllerTest.java
> +            new TypeReference<>() {}
Да, будет работать. У меня Idea кидала предупреждения, когда в скобках что-то было.

Насколько я понял, тут схема примерно такая же как в случае
List<User> userList = new ArrayList<>()
То, что справа можно не указывать явно какого типа у нас будет ArrayList
 (По крайней мере, у меня все тесты проходят, и CI тоже не ругается)

2023-11-07 12:20 UTC, MaxLost commented on src/main/java/edu/spbu/datacontrol/models/User.java
> +    @OneToOne //Мне кажется здесь должно быть @ManyToOne?
Да, будет лучше если тут будет @ManyToOne

2023-11-07 12:20 UTC, MaxLost commented on src/test/java/edu/spbu/datacontrol/repositories/UserRepositoryTest.java
> +        userB.setName("William White");
Проверь что имена не пересекаются с другими тестами

2023-11-07 18:03 UTC, MaxLost approved these changes
Спасибо!

2023-11-07 18:03 UTC, merged