Сreating a mentor-mentor pair
ApCyb-2025-team-3/community-data-control pull request #37
Opened 2023-11-10 20:24 UTC by Homray

Added MentorshipController and MentorshipRepository, in which the creation of a mentor-mentor pair is implemented

2023-11-10 21:01 UTC, Nomlsbad commented on src/main/java/edu/spbu/datacontrol/controllers/MentorshipController.java
> +@RequestMapping("/api/mentorships")
В остальных классах s на конце нет, так что тут тоже убери

2023-11-10 21:04 UTC, Nomlsbad commented on src/main/java/edu/spbu/datacontrol/controllers/MentorshipController.java
> +        if (mentor.getMentorStatus() == MentorshipStatus.MENTOR && mentee.getMentorStatus() == MentorshipStatus.MENTEE) {
Проверки на равенство выглядат очень громоздко. Объяви в классе User метод
public boolean hasRole(MentorStatus role)
и через него проверки делай

2023-11-10 21:07 UTC, Nomlsbad commented on src/main/java/edu/spbu/datacontrol/controllers/MentorshipController.java
> +    public ResponseEntity<String> addMentorship(@RequestBody User mentor, @RequestBody User mentee, @RequestBody Date disbandmentDate) {
Принимвай UserDTO и создавай из него по id экземпляр User, обычный User слишком жирный.
Возможно стоит эти параметры вынести в какой-нибудь MentorshipAdditionDTO

2023-11-10 21:19 UTC, Nomlsbad requested changes
Держите, доделывайте

2023-11-12 12:15 UTC, Nomlsbad requested changes

2023-11-12 12:15 UTC, Nomlsbad commented on src/main/java/edu/spbu/datacontrol/models/MentorshipCreationDTO.java
Прости пожалуйста, я не очень продумал этот момент, нам не поможет этот класс В нём был бы смысл, если бы мы от него моги создать Mentroship, но мы не можем этого сделать, не нагружая класс объёмными полями(чтобы из этого класса сконструировать экземпляр Mentorship, нам придётся хранить либо двух User, либо UserRepository). А предназначен он как раз для того, чтобы быть легковесным. Так что придётся его убрать.

2023-11-12 12:15 UTC, Nomlsbad commented on src/main/java/edu/spbu/datacontrol/controllers/MentorshipController.java
> +    public ResponseEntity<String> createMentorship(@RequestBody MentorshipCreationDTO mentorshipData) {
В саязи с тем, что я балбес, у этого метода поменяй аргуманты. UUID mentor, UUID mentee, Date disbandmentDate.

И лучше публичные методы сверху класса объявлять

2023-11-12 12:15 UTC, Nomlsbad commented on src/main/java/edu/spbu/datacontrol/controllers/MentorshipController.java
> +            return new ResponseEntity<>("Mentorship is added.", HttpStatus.OK);
Ты где-то пользуешься HttpStatus, где-то HttpStatusCode, выбери что-нибудь одно.
Ещё погугли про http коды, лучше 201 возвращать

2023-11-12 12:15 UTC, Nomlsbad commented on src/main/java/edu/spbu/datacontrol/controllers/MentorshipController.java
> +        }
else тут не обязательно, т.к если мы попадём в ветку выше, то выйдем из метода через return. В связи с этим, я бы под if запихал случай, когда мы не можем создать пару

2023-11-12 17:36 UTC, Homray commented on src/main/java/edu/spbu/datacontrol/controllers/MentorshipController.java
> +    public ResponseEntity<String> createMentorship(@RequestBody MentorshipCreationDTO mentorshipData) {
На всякий случай уточню. Мне нужно принимать просто id ментора и менти, а не UserDTO mentor и UserDTO mentee?

2023-11-12 18:48 UTC, Nomlsbad requested changes

2023-11-12 18:48 UTC, Nomlsbad commented on src/main/java/edu/spbu/datacontrol/controllers/MentorshipController.java
> +    public ResponseEntity<String> createMentorship(@RequestBody UUID mentorId, @RequestBody UUID menteeId, @RequestBody Date disbadmentData) {
Во-первых, нужно @RequestParam перед параметрами, во-вторых, ты disbandment неправильно написал

2023-11-12 18:59 UTC, Nomlsbad approved these changes

2023-11-12 18:59 UTC, merged