Accept and exclude user to or from group endpoint
ApCyb-2025-team-3/community-data-control pull request #47
Opened 2023-11-13 21:20 UTC by Chernovuk

2023-11-14 11:28 UTC, Nomlsbad requested changes

2023-11-14 11:28 UTC, Nomlsbad commented on src/main/java/edu/spbu/datacontrol/models/UserAdditionDTO.java
> +
Вот это нам не нужно

2023-11-14 11:28 UTC, Nomlsbad commented on src/main/java/edu/spbu/datacontrol/controllers/GroupController.java
> +        //Как мы вообще определяем, когда DTO класс передаем, а когда ID?
Да в принципе без разницы. Если хочешь можно на id переделать. DTO, наверное, прям 100% стоит использовать, когда нам какие-то ещё поля необходими, кроме id.
И ещё ты можешь в пул реквесте писать такие вопросы, а не в коде

2023-11-14 11:28 UTC, Nomlsbad commented on src/main/java/edu/spbu/datacontrol/controllers/GroupController.java
> +        //Тут тот же самый вопрос
Ну всё-всё. Переделай на id. Ещё согласуй порядок параметров, а то в acceptUser у тебя сначала группа, потом User, тут наоборот

2023-11-14 11:28 UTC, Nomlsbad commented on src/main/java/edu/spbu/datacontrol/controllers/GroupController.java
> +        if (group == null || !group.isActive()) {
Если group.isActive() == false, то оно не not found, а уже расформирована.

2023-11-14 11:28 UTC, Nomlsbad commented on src/main/java/edu/spbu/datacontrol/controllers/GroupController.java
> +        //Если да, то вызывать disbandGroup или просто ставить, что она неактивна?
Надо проверять, что мы не исключаем тим лида, тогда он будет всегда последний. И пока сделаем так, что нельзя его исключить. Вообще если делать нормально, то нужно при попытке исключить лида, просить пользователся назначить нового, а при удалении последнего члена, уведомлять, что группа будет рассформирована. Но я пока не знаю, как так сделать, если ты сам найдёшь, то будет здорово

2023-11-14 11:28 UTC, Nomlsbad commented on src/main/java/edu/spbu/datacontrol/controllers/MentorshipController.java
> +    @PatchMapping("/becomeMentee")
Убери пока это, сделай в отдельном патче. Вметсе с переносом save

2023-11-14 12:53 UTC, Nomlsbad requested changes
Есть ещё проблема с таблицами. У тебя создаются 2 таблицы для связи юзеров и групп, такого быть не должно. В одной из статьей есть об этом информация, почитай.
![image](https://github.com/ApCyb-2025-team-3/community-data-control/assets/103033740/945738a9-fc6a-4bda-9e80-04df97b54986)

2023-11-14 13:36 UTC, MaxLost commented
> Есть ещё проблема с таблицами. У тебя создаются 2 таблицы для связи юзеров и групп: users_groups и groups_members, такого быть не должно. В одной из статьей есть об этом информация, почитай.
> ![image](https://github.com/ApCyb-2025-team-3/community-data-control/assets/103033740/945738a9-fc6a-4bda-9e80-04df97b54986)
> 

Это скорее всего из-за того, что был добавлен список групп в User, я говорил что вы можете это через GroupRepository делать

2023-11-16 10:35 UTC, Chernovuk commented on src/main/java/edu/spbu/datacontrol/models/User.java
> +    @JoinColumn(name = "user_id")
Строчку эту я добавить добавил, но там две таблицы, по-моему, по причине того, что у нас есть список юзеров-членов, как поле группы, и список групп у самого юзера. Потому что ни одна из них не пропадает при добавлении этой аннотации (я даже попробовал немного поиграться с ней, но прям чтобы сильно)

2023-11-16 10:45 UTC, MaxLost commented on src/main/java/edu/spbu/datacontrol/models/User.java
> +    @JoinColumn(name = "user_id")
Попробуй сбросить схему БД, как это делать спроси у Ильи

2023-11-18 19:04 UTC, Nomlsbad approved these changes

2023-11-18 19:05 UTC, merged