restored updateGroup
ApCyb-2025-team-3/community-data-control pull request #57
Opened 2023-11-19 10:21 UTC by AnSaladim

2023-11-19 12:05 UTC, Nomlsbad requested changes

2023-11-19 12:05 UTC, Nomlsbad commented on src/main/java/edu/spbu/datacontrol/controllers/GroupController.java
> +                return new ResponseEntity<>("A group with this name already exists!", HttpStatusCode.valueOf(409));
Нам достаточно проверить, существует ли хотябы 1 такая группа, так что можно getGroupByName использовать и на null проверять

2023-11-19 15:56 UTC, vadim65060 commented on src/main/java/edu/spbu/datacontrol/controllers/GroupController.java
зачем тут пропускаются строки??

2023-11-19 16:00 UTC, vadim65060 commented on src/main/java/edu/spbu/datacontrol/repositories/GroupRepository.java
ещё ненужные строки

2023-11-20 01:51 UTC, Nomlsbad requested changes
Ну поправь про что тебе написали

2023-11-20 11:48 UTC, Nomlsbad approved these changes

2023-11-21 06:53 UTC, closed without merging