Added changing of teamLead role in assignTeamLead
ApCyb-2025-team-3/community-data-control pull request #69
Opened 2023-11-20 17:49 UTC by Chernovuk

2023-11-20 20:43 UTC, MaxLost commented on src/main/java/edu/spbu/datacontrol/controllers/GroupController.java
> +        group.getTeamLead().setRole(Role.MEMBER);
Вообще так не стоит делать.
Member - роль для участников сообщества, которые не являются работниками.

(НА БУДУЩЕЕ, СЕЙЧАС МОЖНО НЕ ДЕЛАТЬ):
Для манипуляции с пользователями существует контроллер и следует использовать его для таких вещей

2023-11-20 20:44 UTC, MaxLost commented on src/main/java/edu/spbu/datacontrol/controllers/GroupController.java
> +            userRepository.save(teamLead);
А зачем? Он же уже зарегистрирован

2023-11-20 20:46 UTC, MaxLost commented on src/main/java/edu/spbu/datacontrol/controllers/GroupController.java
> +        group.getTeamLead().setRole(Role.MEMBER);
Ну и да, манипуляции с ролями так не сохранятся в БД)

Тут вот как раз нужно сохранение, причём и с записью в журнал о событии

2023-11-20 23:51 UTC, Nomlsbad requested changes

2023-11-20 23:51 UTC, Nomlsbad commented on src/main/java/edu/spbu/datacontrol/controllers/GroupController.java
> +        group.getTeamLead().setRole(Role.MEMBER);
Нужно DEVELOPER устанавливать

2023-11-22 16:44 UTC, Nomlsbad approved these changes

2023-11-22 16:44 UTC, merged